### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by Mudrekh** [patrickmichalina/onvif-rx#45]
Hi @patrickmichalina,

I was messing around with your library and ran into an issue with optional parameters, specifically using [Media.GetVideoEncoderConfigurationOptions](https://github.com/patrickmichalina/onvif-rx/blob/b41842ea88a0852a9fc52a80786007ed3298f7cf/src/api/media.ts#L593). Originally, I could only get the function to complete by specifying both parameters, but it seems based on the specification that I should be able to use the function without needing to supply the params to get 'generic' configuration options for the device. 

After some digging, it seems like the issue can be traced to [function](https://github.com/patrickmichalina/onvif-rx/blob/b41842ea88a0852a9fc52a80786007ed3298f7cf/src/soap/request.ts#L120). When passed no parameters in the calling function, the resulting object passed to this function is something like 
```
{ 
  trt_ConfigurationToken: undefined,
  trt_ProfileToken: undefined 
}
```

which causes the function to throw an error at `Object.keys` later in the recursive chain when evaluating undefined. I believe the problem can be solved by replacing the [line](https://github.com/patrickmichalina/onvif-rx/blob/b41842ea88a0852a9fc52a80786007ed3298f7cf/src/soap/request.ts#L137) with `return params ? reducer(params)(reqNode)() : ''`. However, I am not to familiar with typescipt as well as the other effects this may have in the library. Does this seem correct? Another option would be to add a line like `if (!obj[key]) return acc;` before this [line](https://github.com/patrickmichalina/onvif-rx/blob/b41842ea88a0852a9fc52a80786007ed3298f7cf/src/soap/request.ts#L124)

The resulting strings w/params and without params after making this change:

`<trt:GetVideoSourceConfigurationOptions><trt:ProfileToken>recording</trt:ProfileToken><trt:ConfigurationToken>0</trt:ConfigurationToken></trt:GetVideoSourceConfigurationOptions>`

`<trt:GetVideoSourceConfigurationOptions></trt:GetVideoSourceConfigurationOptions>`

which my device correctly interprets.

**Comment by patrickmichalina** [comment]
Thanks for the code
